#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# sling defaults
# Note, init script uses :
# $JAVA_ARGS $JAVA_DEBUG_ARGS -jar $SLING_JAR $SLING_DEFAULT_ARGS

#
# All configuration items are setup in /etc/sling/*
# The files are processed aggregated using /etc/sling/Makefile to generate
# the configuration specific start modes.
#
# Runtime startup mode options:
# 	crank 			- tar files for nodes and data
# 	crank-s3 		- tar files for nodes, s3 for data
#	crank-mongo 	- mongo for nodes and data
#	crank-s3-mongo 	- mongo for nodes, s3 for data
#
#	key:
#	node store - for node properties and tree structure
#	data store - for binaries
#

RUNMODE=crank

JAVA_ARGS="-Xmx384M "
# Uncomment for debugging:
JAVA_ARGS+=" -agentlib:jdwp=transport=dt_socket,address=30303,server=y,suspend=n"

## fix in crank.d now

#SLING_DATA=/var/lib/sling
#SLING_PORT=8090
#SLING_LISTEN_ADDR=0.0.0.0
#SLING_DEFAULT_ARGS="-c $SLING_DATA -p $SLING_PORT -a $SLING_LISTEN_ADDR $DEBUG_ARGS"
#SLING_DEFAULT_ARGS="-c $SLING_DATA -p 8090 -a 0.0.0.0 $DEBUG_ARGS"


# Allow gogo shell to run in noninteractive env:
# From: http://apache-felix.18485.x6.nabble.com/Gogo-shell-on-standard-input-output-streams-td4845969.html#a4845970
JAVA_ARGS+=" -Dgosh.args=--nointeractive"

# Other defaults.

set -a
##
## Parameters used bu sling init.d script.
##

# Identification

SLING_USER=sling
SLING_GROUP=sling

# Base locations

SLING_HOME=/opt/sling
SLING_CFG=/etc/sling
SLING_DEFAULTS=/etc/default/sling
SLING_SCRIPTS=${SLING_HOME}/scripts
# Define where to load dependencies from

M2REPO="${SLING_HOME}/contrib"
CRANKSTART_ENV=${SLING_SCRIPTS}/crankstart.sh

SLING_LOG_DIR=/var/log/sling
LOG_FILE=$SLING_LOG_DIR/${NAME}-start.log
SLING_DATA=/var/lib/sling

JAVA_ARGS+=" -Dsling.home=$SLING_DATA -Dport=8090"

# Setup default locations for sling crankstart Makefile
set +a
